import { COORDINATES_KEYNAME, LATITUDE_KEYNAME, LONGTITUDE_KEYNAME } from '../../constants/userKeys';

const users = [
    {
        "_id": "59fdc1b4481cf2d67801d4ba",
        "index": 0,
        "guid": "3d783f86-c1ca-495f-a1f6-38d9474e5dcf",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 30,
        "name": "Krista Morton",
        "gender": "female",
        "company": "OPTYK",
        "email": "kristamorton@optyk.com",
        "phone": "+1 (841) 561-3064",
        "about": "Quis eu consequat quis amet amet minim est qui id. Nostrud ex labore exercitation excepteur eu magna anim dolore deserunt magna. In aliqua ea mollit est laboris. Nostrud consectetur veniam enim aliquip excepteur consectetur do dolor exercitation mollit nostrud id quis Lorem. Cillum velit est incididunt quis eiusmod do excepteur irure minim cillum enim sunt.\r\n",
        "registered": "2016-04-08T11:26:11 -03:00",
        "latitude": 39.243628,
        "longitude": 52.772256
    },
    {
        "_id": "59fdc1b4a0514d7945f98812",
        "index": 1,
        "guid": "917ffa27-426f-445d-b7a6-581f8696b991",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 25,
        "name": "Salinas Stanley",
        "gender": "male",
        "company": "INSOURCE",
        "email": "salinasstanley@insource.com",
        "phone": "+1 (823) 481-2961",
        "about": "Pariatur ad sunt nulla deserunt incididunt consequat reprehenderit reprehenderit. Ad labore excepteur est labore dolore ex velit Lorem nisi culpa elit commodo ex irure. Minim magna ut amet aliqua irure exercitation do anim dolor aute consequat cupidatat. Dolore commodo cupidatat aute eiusmod non in nostrud eiusmod ea dolore qui. Commodo amet elit ad excepteur. Aliquip adipisicing do dolor occaecat.\r\n",
        "registered": "2014-04-09T12:53:29 -03:00",
        "latitude": 66.024153,
        "longitude": -78.924516
    },
    {
        "_id": "59fdc1b42f7704956e9dc36a",
        "index": 2,
        "guid": "8d018918-e600-48ac-a037-8ada31c8d522",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 26,
        "name": "Suzette Bruce",
        "gender": "female",
        "company": "HANDSHAKE",
        "email": "suzettebruce@handshake.com",
        "phone": "+1 (930) 482-2483",
        "about": "Dolor occaecat esse deserunt sint aliqua consectetur sit sint ullamco sit consequat. Cupidatat dolor aliquip proident dolore dolore adipisicing ullamco laboris amet. Incididunt id magna ullamco esse ex adipisicing incididunt pariatur. Adipisicing laboris cupidatat amet cillum laboris aliquip esse et sunt ad incididunt. Esse Lorem sint aliqua voluptate cupidatat nulla officia id aliqua. Elit deserunt esse culpa exercitation sunt labore anim anim anim labore laboris quis.\r\n",
        "registered": "2014-09-09T08:36:34 -03:00",
        "latitude": -24.898173,
        "longitude": -27.620262
    },
    {
        "_id": "59fdc1b4ee8e29c8bf515be4",
        "index": 3,
        "guid": "45500154-f392-460a-96c0-7816e1a4b3cd",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 24,
        "name": "Henrietta Gilbert",
        "gender": "female",
        "company": "NUTRALAB",
        "email": "henriettagilbert@nutralab.com",
        "phone": "+1 (987) 592-3864",
        "about": "Do eiusmod sunt esse eu pariatur deserunt esse. Lorem Lorem sit ut non adipisicing pariatur ex excepteur labore dolor irure. Aliquip minim elit irure nostrud aliqua sint commodo excepteur sit velit enim. Et nulla cillum proident consectetur labore ipsum amet ex. Exercitation ea voluptate cillum laborum fugiat nisi deserunt proident. Duis ad anim occaecat ipsum deserunt dolore do. Adipisicing ad quis sit consectetur ea tempor amet tempor magna ad eu voluptate Lorem deserunt.\r\n",
        "registered": "2016-08-05T03:00:09 -03:00",
        "latitude": 33.028789,
        "longitude": -146.745587
    },
    {
        "_id": "59fdc1b47401e5bed907a3e3",
        "index": 4,
        "guid": "234a7a5a-ee6d-4000-bf3f-729ddde27ef7",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 37,
        "name": "Camacho Mcconnell",
        "gender": "male",
        "company": "ZAGGLES",
        "email": "camachomcconnell@zaggles.com",
        "phone": "+1 (853) 437-3777",
        "about": "Deserunt sunt pariatur sit ipsum officia fugiat anim est. Id commodo anim nulla consequat duis anim aliqua irure dolor excepteur nostrud. Reprehenderit id esse commodo pariatur aliquip amet cillum qui proident irure in sit. Excepteur occaecat mollit adipisicing enim id id et tempor non. Aliquip proident dolor nostrud nostrud deserunt proident amet laborum ipsum id. Labore cupidatat velit pariatur veniam tempor irure qui laborum nostrud. Exercitation dolor veniam laboris nisi aliquip.\r\n",
        "registered": "2016-11-20T03:28:13 -02:00",
        "latitude": -82.877274,
        "longitude": -147.366045
    },
    {
        "_id": "59fdc1b419d58dd37d9e5ff0",
        "index": 5,
        "guid": "450dc78c-ef4e-4db9-93dc-66e0fa33aaef",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 32,
        "name": "Pratt Mays",
        "gender": "male",
        "company": "PERMADYNE",
        "email": "prattmays@permadyne.com",
        "phone": "+1 (975) 581-3461",
        "about": "Sint consequat reprehenderit veniam magna occaecat elit. Ea commodo anim consectetur eiusmod magna qui commodo nulla est consectetur fugiat et exercitation esse. Occaecat officia ut Lorem ullamco eiusmod esse esse eu.\r\n",
        "registered": "2014-02-03T11:02:55 -02:00",
        "latitude": -37.228926,
        "longitude": 97.078222
    },
    {
        "_id": "59fdc1b452fde23209b40c67",
        "index": 6,
        "guid": "10a2fb07-86f2-4c32-90c8-304693765767",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 33,
        "name": "Mcdaniel Park",
        "gender": "male",
        "company": "FUTURITY",
        "email": "mcdanielpark@futurity.com",
        "phone": "+1 (846) 532-3901",
        "about": "Excepteur aliqua pariatur pariatur nisi est sit culpa commodo. Deserunt ullamco amet incididunt qui cupidatat. Eu sint eiusmod elit Lorem velit irure est duis adipisicing cillum esse ipsum. Commodo sint esse labore ullamco magna nulla ex Lorem. Voluptate voluptate id elit et qui mollit ad est aliqua deserunt irure dolor deserunt.\r\n",
        "registered": "2014-04-05T07:42:22 -03:00",
        "latitude": -51.216855,
        "longitude": -107.915573
    },
    {
        "_id": "59fdc1b4ed57c4b9cebe0123",
        "index": 7,
        "guid": "7a7c07d5-85a6-4fbe-8f1c-43cc1527f40f",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 23,
        "name": "Kerr Hodges",
        "gender": "male",
        "company": "ISOSPHERE",
        "email": "kerrhodges@isosphere.com",
        "phone": "+1 (845) 499-2005",
        "about": "Do velit id voluptate fugiat exercitation qui dolore aliquip duis ullamco. Proident irure quis quis veniam minim aliqua irure nulla cupidatat. Dolore aliquip incididunt deserunt qui nulla magna ad voluptate quis in ea mollit proident. Irure velit id commodo incididunt do excepteur. Veniam consequat velit tempor sunt ut amet aliquip amet mollit ex nisi est dolor. Elit aliquip ea proident ut ipsum officia.\r\n",
        "registered": "2014-03-31T03:23:20 -03:00",
        "latitude": 77.16883,
        "longitude": 8.708228
    },
    {
        "_id": "59fdc1b4131780fe554fb062",
        "index": 8,
        "guid": "f8f44210-b63a-4219-b2c9-ba4d49f1afa5",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Gamble Cherry",
        "gender": "male",
        "company": "CYTREK",
        "email": "gamblecherry@cytrek.com",
        "phone": "+1 (844) 465-3723",
        "about": "Aute nostrud laborum occaecat eiusmod ut labore do pariatur magna ea labore. Lorem reprehenderit cupidatat do velit. Culpa ipsum dolore nisi reprehenderit velit id. Voluptate non labore deserunt ullamco fugiat officia duis excepteur voluptate. Duis eiusmod fugiat duis ullamco consequat tempor sint cupidatat ipsum pariatur est velit id. Dolore minim labore pariatur fugiat commodo est mollit labore.\r\n",
        "registered": "2015-11-04T08:11:40 -02:00",
        "latitude": 72.546738,
        "longitude": 39.585341
    },
    {
        "_id": "59fdc1b4392ff1ff32ed5831",
        "index": 9,
        "guid": "1b4e3c14-ca75-4642-be90-8ac2e8e79d8b",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 35,
        "name": "Baxter Vang",
        "gender": "male",
        "company": "COMTRAK",
        "email": "baxtervang@comtrak.com",
        "phone": "+1 (883) 444-2691",
        "about": "Id cillum officia non exercitation nisi esse ea pariatur ipsum adipisicing enim laborum nostrud consectetur. Exercitation incididunt commodo labore adipisicing incididunt cupidatat nulla magna. Ex ea cupidatat reprehenderit mollit est labore ullamco eiusmod id.\r\n",
        "registered": "2015-05-18T01:25:45 -03:00",
        "latitude": 61.134775,
        "longitude": -60.439274
    },
    {
        "_id": "59fdc1b4ce4410a294696fff",
        "index": 10,
        "guid": "0eadd62f-3bf4-4b0a-ae1c-50a12e709120",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 37,
        "name": "Lolita Porter",
        "gender": "female",
        "company": "AVIT",
        "email": "lolitaporter@avit.com",
        "phone": "+1 (898) 448-2459",
        "about": "Consectetur sit cillum consectetur irure ex labore. Cillum qui ullamco consequat laboris cillum aliquip id ex. Quis elit id non qui elit aute ad duis ipsum quis.\r\n",
        "registered": "2014-03-30T09:27:59 -03:00",
        "latitude": 28.429108,
        "longitude": -17.832951
    },
    {
        "_id": "59fdc1b44ba6760f85002112",
        "index": 11,
        "guid": "11d6ea81-c7f1-476c-8204-bc04a66c173d",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Ryan Morgan",
        "gender": "male",
        "company": "EXTRAGEN",
        "email": "ryanmorgan@extragen.com",
        "phone": "+1 (880) 445-3471",
        "about": "Proident pariatur esse ut qui id. Aute nostrud duis minim qui enim irure tempor aliquip consectetur aliqua consequat. Tempor anim ipsum magna mollit sit sint nostrud labore anim sint. Minim adipisicing mollit voluptate dolor laboris reprehenderit irure nulla laboris irure est id. Aute irure laboris officia pariatur eiusmod ex irure sit elit elit sit excepteur officia. Id velit amet deserunt cupidatat proident veniam labore ullamco pariatur reprehenderit.\r\n",
        "registered": "2015-10-11T06:28:11 -03:00",
        "latitude": -42.859756,
        "longitude": -132.850491
    },
    {
        "_id": "59fdc1b403406f91b727c4aa",
        "index": 12,
        "guid": "46025476-ca96-47f9-a36c-d76fd2968dcb",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 24,
        "name": "Jaime Rollins",
        "gender": "female",
        "company": "WARETEL",
        "email": "jaimerollins@waretel.com",
        "phone": "+1 (850) 538-2228",
        "about": "Lorem sint aliqua commodo aute. Velit sit ea voluptate irure tempor nisi adipisicing pariatur elit incididunt. Tempor enim eu in esse nulla pariatur. Occaecat sunt consectetur do do labore in duis sint incididunt deserunt ea in elit. Magna sit eiusmod aute do cupidatat ea pariatur Lorem irure voluptate mollit.\r\n",
        "registered": "2016-03-03T10:58:48 -02:00",
        "latitude": -30.379334,
        "longitude": 5.424809
    },
    {
        "_id": "59fdc1b4f9f01682550a242c",
        "index": 13,
        "guid": "11547df3-faa1-475a-a11e-c72fc4deeb47",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 39,
        "name": "Dyer Wilkinson",
        "gender": "male",
        "company": "EXOVENT",
        "email": "dyerwilkinson@exovent.com",
        "phone": "+1 (842) 529-2019",
        "about": "Aliquip commodo sunt officia minim reprehenderit quis. Enim eu elit occaecat deserunt laborum non minim aliquip duis eiusmod mollit est ex nulla. Consectetur irure aute cupidatat nostrud labore veniam reprehenderit commodo consequat officia dolore qui mollit. Lorem tempor proident elit labore consectetur aliqua quis officia qui anim veniam in elit.\r\n",
        "registered": "2017-07-30T01:27:12 -03:00",
        "latitude": 7.186988,
        "longitude": 138.759927
    },
    {
        "_id": "59fdc1b4f3a82517b15693ac",
        "index": 14,
        "guid": "c88a196f-597e-445e-a582-4ed0c4a3a942",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 34,
        "name": "Brennan Boyer",
        "gender": "male",
        "company": "GAZAK",
        "email": "brennanboyer@gazak.com",
        "phone": "+1 (948) 486-3372",
        "about": "Ea laboris occaecat cillum enim commodo aliquip dolor consectetur. Excepteur elit occaecat aute tempor ea sit. Cupidatat labore consequat pariatur elit adipisicing exercitation amet. Occaecat sunt ut enim Lorem aliqua dolor cupidatat minim duis. Sunt aliqua exercitation qui ipsum nulla mollit.\r\n",
        "registered": "2015-05-05T06:01:27 -03:00",
        "latitude": 63.846261,
        "longitude": 132.414924
    },
    {
        "_id": "59fdc1b467c46071da7e26c6",
        "index": 15,
        "guid": "91ad9228-cc00-4670-a148-09e5e13c82cd",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 27,
        "name": "Elaine Lynch",
        "gender": "female",
        "company": "QUAILCOM",
        "email": "elainelynch@quailcom.com",
        "phone": "+1 (862) 414-2805",
        "about": "Qui cupidatat laborum irure est ut eiusmod. Reprehenderit sunt eiusmod officia elit reprehenderit voluptate ad. Elit nulla qui veniam deserunt amet. Nisi commodo cupidatat commodo exercitation occaecat velit tempor officia pariatur sit pariatur commodo cupidatat. Dolore Lorem eiusmod nulla et nisi incididunt non laborum adipisicing cillum ullamco exercitation.\r\n",
        "registered": "2016-07-11T04:16:59 -03:00",
        "latitude": 27.170682,
        "longitude": 40.087808
    },
    {
        "_id": "59fdc1b40adb0b75c419e869",
        "index": 16,
        "guid": "8381488f-cae1-4012-b926-6bdbac67cd64",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Gabrielle Harper",
        "gender": "female",
        "company": "EURON",
        "email": "gabrielleharper@euron.com",
        "phone": "+1 (998) 568-3372",
        "about": "Cupidatat excepteur aliqua dolore cillum Lorem exercitation. Excepteur et qui eiusmod adipisicing. Cupidatat laborum ullamco deserunt do quis velit cupidatat irure. Occaecat anim aliquip duis duis voluptate ea velit dolore consectetur ullamco non sit sint. Veniam deserunt cillum amet tempor. Non nisi sit magna id enim aliquip aliquip. Exercitation est veniam labore sit officia et et nulla aute ad anim consectetur.\r\n",
        "registered": "2017-11-03T10:27:08 -02:00",
        "latitude": -21.834974,
        "longitude": 170.097314
    },
    {
        "_id": "59fdc1b44d1c5b650781ad22",
        "index": 17,
        "guid": "718d6e5d-18c4-45cf-8deb-0669f852dba2",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 28,
        "name": "Mckay Tucker",
        "gender": "male",
        "company": "ACCUPHARM",
        "email": "mckaytucker@accupharm.com",
        "phone": "+1 (942) 455-3713",
        "about": "Et tempor mollit consequat adipisicing. Mollit enim commodo esse reprehenderit eu eiusmod tempor ipsum anim. Eiusmod deserunt dolore fugiat ad ut quis amet. Lorem commodo ut duis ad veniam cupidatat nostrud occaecat dolor duis ut occaecat. Ullamco anim qui eu cupidatat consequat id ullamco dolor voluptate nisi. Sunt minim ad deserunt cillum culpa tempor culpa exercitation et eu laboris proident enim. Tempor elit eiusmod labore incididunt reprehenderit.\r\n",
        "registered": "2014-07-22T12:51:39 -03:00",
        "latitude": -52.327438,
        "longitude": -167.199213
    },
    {
        "_id": "59fdc1b4048efe8bce649613",
        "index": 18,
        "guid": "98c163bf-e12d-4bc9-b71a-a9773005f329",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 34,
        "name": "Eloise Jacobson",
        "gender": "female",
        "company": "IMPERIUM",
        "email": "eloisejacobson@imperium.com",
        "phone": "+1 (938) 488-3214",
        "about": "Quis in eiusmod exercitation irure sint tempor deserunt. Ullamco cupidatat eiusmod anim ex mollit officia eu irure ut veniam. Qui cupidatat reprehenderit excepteur magna laborum ad nisi Lorem velit do ea tempor tempor. Exercitation sunt exercitation ex non. Lorem aliquip sint est dolor occaecat quis consequat ex aliquip. Aliquip id proident enim irure nisi est culpa dolore ea ex.\r\n",
        "registered": "2017-01-13T07:37:30 -02:00",
        "latitude": 13.563104,
        "longitude": -162.901075
    },
    {
        "_id": "59fdc1b41060a20bb36ae315",
        "index": 19,
        "guid": "2460f645-7bdd-4437-8f70-69f1853bf7a3",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 32,
        "name": "Aileen Richmond",
        "gender": "female",
        "company": "TUBESYS",
        "email": "aileenrichmond@tubesys.com",
        "phone": "+1 (861) 447-2124",
        "about": "Minim ea eiusmod ut laboris et qui consequat ad ea. Lorem eu dolor id eiusmod et id qui laborum. Laborum commodo dolore sit ex non elit aliquip nostrud reprehenderit quis officia sint anim. Ipsum aute irure quis sunt mollit et tempor ullamco irure. Nisi anim esse anim nisi in anim.\r\n",
        "registered": "2017-07-28T05:09:54 -03:00",
        "latitude": -84.450893,
        "longitude": -140.308544
    },
    {
        "_id": "59fdc1b457744a984c00a7ed",
        "index": 20,
        "guid": "b424dbd3-7aff-44a2-a20d-3c67498a67d5",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 28,
        "name": "Candace Mercer",
        "gender": "female",
        "company": "UNQ",
        "email": "candacemercer@unq.com",
        "phone": "+1 (854) 596-3025",
        "about": "Eu enim cillum enim nostrud ullamco pariatur laboris tempor dolore officia sunt do duis. Sit adipisicing tempor Lorem deserunt laborum pariatur do tempor. Quis est id id magna nulla id sint ex quis ex nisi. Eu nisi est Lorem veniam non dolor nostrud cillum dolor nisi et dolor ea. Laborum ea ut aliqua nostrud aute Lorem.\r\n",
        "registered": "2015-04-08T03:09:57 -03:00",
        "latitude": -61.083009,
        "longitude": 137.444889
    },
    {
        "_id": "59fdc1b4ee705c0cdb9e02a5",
        "index": 21,
        "guid": "7019be1d-bf63-417b-9b8d-554934c9a5ce",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Stanley Raymond",
        "gender": "male",
        "company": "ESCHOIR",
        "email": "stanleyraymond@eschoir.com",
        "phone": "+1 (989) 515-3765",
        "about": "Irure enim in ea duis. Laboris aute incididunt sit laborum proident nostrud Lorem. Sit quis officia quis mollit adipisicing est quis.\r\n",
        "registered": "2015-03-03T05:22:14 -02:00",
        "latitude": -68.568921,
        "longitude": -150.249808
    },
    {
        "_id": "59fdc1b409ac4c43c56c2a33",
        "index": 22,
        "guid": "f7ef5b70-1036-48ac-8ca1-e37614d21a84",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 32,
        "name": "Jami James",
        "gender": "female",
        "company": "EXTRAGENE",
        "email": "jamijames@extragene.com",
        "phone": "+1 (841) 515-3811",
        "about": "Anim excepteur ut anim mollit qui nostrud Lorem adipisicing sunt aute ea. Cupidatat occaecat consequat et ipsum. Sunt quis qui consectetur labore aute consequat mollit ad culpa in nulla ad laboris. Pariatur laborum pariatur cupidatat ea exercitation incididunt cupidatat. Cillum dolore elit proident eiusmod reprehenderit proident in fugiat aliqua nisi elit reprehenderit Lorem ea. Commodo minim eiusmod sint consectetur ipsum ullamco culpa do sunt est veniam Lorem ut.\r\n",
        "registered": "2015-02-26T02:18:38 -02:00",
        "latitude": -70.859152,
        "longitude": -18.578926
    },
    {
        "_id": "59fdc1b4012cccf240c2e3f7",
        "index": 23,
        "guid": "628fba92-61b2-4a14-bd95-62471a0c8f6b",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 37,
        "name": "Henson Monroe",
        "gender": "male",
        "company": "PUSHCART",
        "email": "hensonmonroe@pushcart.com",
        "phone": "+1 (982) 468-3370",
        "about": "Sit excepteur elit laboris ullamco mollit ad laboris ea ad aliqua. Elit ipsum sunt irure dolore exercitation nostrud nostrud consectetur incididunt tempor. Quis est incididunt excepteur officia nulla id consectetur elit in qui ea nostrud.\r\n",
        "registered": "2017-10-08T02:14:15 -03:00",
        "latitude": 65.591671,
        "longitude": -53.841355
    },
    {
        "_id": "59fdc1b4e1857f9433111563",
        "index": 24,
        "guid": "732eae1e-1fea-4277-9884-1647075fccab",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 39,
        "name": "Kim Robinson",
        "gender": "female",
        "company": "UNIWORLD",
        "email": "kimrobinson@uniworld.com",
        "phone": "+1 (865) 428-2956",
        "about": "Reprehenderit qui culpa aute pariatur pariatur qui elit qui dolore. Minim labore eu exercitation eiusmod deserunt laboris in quis. Nisi nostrud occaecat et ullamco. In laboris tempor ullamco dolore.\r\n",
        "registered": "2016-11-11T09:08:49 -02:00",
        "latitude": -61.232924,
        "longitude": 128.246651
    },
    {
        "_id": "59fdc1b4b11e8e6e95088c61",
        "index": 25,
        "guid": "b9e0ff7f-5b89-4210-93a1-6e64908dcb61",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 39,
        "name": "Etta Hebert",
        "gender": "female",
        "company": "ILLUMITY",
        "email": "ettahebert@illumity.com",
        "phone": "+1 (945) 429-3383",
        "about": "Officia enim velit mollit laboris sint exercitation occaecat sit nulla culpa adipisicing deserunt cillum. Enim officia pariatur sint consequat cillum elit laborum. Exercitation consectetur mollit nulla anim nisi irure veniam.\r\n",
        "registered": "2016-05-24T08:17:03 -03:00",
        "latitude": -4.252971,
        "longitude": 162.660183
    },
    {
        "_id": "59fdc1b446093d9d52abdb52",
        "index": 26,
        "guid": "a4af49b2-56ad-499d-a1aa-922d1c795794",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 31,
        "name": "Holden Faulkner",
        "gender": "male",
        "company": "QUANTASIS",
        "email": "holdenfaulkner@quantasis.com",
        "phone": "+1 (871) 506-3950",
        "about": "Magna ad voluptate consectetur nostrud ea aute dolor aliquip consequat Lorem minim. Ad laborum proident mollit consequat occaecat et ex exercitation laborum elit. Pariatur in cillum anim cupidatat ea ut officia. Excepteur labore tempor aute qui fugiat amet dolore aute. Do aliquip mollit aliquip esse commodo amet aute occaecat. Ullamco fugiat officia minim qui sit aliqua id qui excepteur anim elit.\r\n",
        "registered": "2015-05-16T12:33:55 -03:00",
        "latitude": 24.48178,
        "longitude": 46.174759
    },
    {
        "_id": "59fdc1b4b7de3b96c3c6a8d5",
        "index": 27,
        "guid": "11a54c08-79ee-4e48-bafc-306cf5085c80",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 31,
        "name": "Tamra Hardin",
        "gender": "female",
        "company": "MAGNINA",
        "email": "tamrahardin@magnina.com",
        "phone": "+1 (931) 568-3559",
        "about": "Nostrud tempor eiusmod sit id voluptate quis consequat consectetur esse quis sunt velit. Eu cupidatat elit cupidatat consectetur ullamco Lorem ea fugiat ipsum nostrud ea dolore in pariatur. Labore culpa commodo ullamco quis labore amet dolore. Velit ut sint incididunt sit. Ex Lorem veniam ad et non esse consequat consequat deserunt cillum reprehenderit aliqua. Esse reprehenderit ex ipsum eu velit. Irure sunt reprehenderit ea veniam ut id voluptate velit nulla ipsum laborum nisi.\r\n",
        "registered": "2017-03-22T01:33:17 -02:00",
        "latitude": -74.263292,
        "longitude": -128.106991
    },
    {
        "_id": "59fdc1b4fa34b9ab6f88c43d",
        "index": 28,
        "guid": "2557463e-4bba-4f49-a177-2d42f81782aa",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 33,
        "name": "Perkins Bush",
        "gender": "male",
        "company": "MAROPTIC",
        "email": "perkinsbush@maroptic.com",
        "phone": "+1 (982) 596-3202",
        "about": "Minim laboris consequat consequat et esse ea do non ullamco laborum consectetur. Laboris enim ad occaecat exercitation excepteur aliquip. Adipisicing nostrud Lorem ipsum nostrud. Ullamco commodo reprehenderit Lorem laboris eu tempor laboris anim et aliqua. Enim fugiat dolor cupidatat exercitation aliquip nulla Lorem anim sunt pariatur. Ex fugiat quis sunt cillum.\r\n",
        "registered": "2016-09-05T04:36:25 -03:00",
        "latitude": 80.705119,
        "longitude": 169.146333
    },
    {
        "_id": "59fdc1b4a5ec7b3e32b10cfe",
        "index": 29,
        "guid": "6a0a97e6-9838-41fa-b024-99dba188f0e1",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 33,
        "name": "Pamela Hart",
        "gender": "female",
        "company": "KAGE",
        "email": "pamelahart@kage.com",
        "phone": "+1 (978) 440-3610",
        "about": "Amet incididunt sint ullamco nostrud qui ea sint commodo aliquip laboris voluptate pariatur. Ullamco ad ad ullamco minim labore. Ullamco excepteur id non incididunt voluptate sit culpa voluptate dolor ut sint exercitation eiusmod.\r\n",
        "registered": "2014-07-29T07:44:51 -03:00",
        "latitude": 46.07614,
        "longitude": 179.35063
    },
    {
        "_id": "59fdc1b44729b34010f6f198",
        "index": 30,
        "guid": "0b8a29d8-81b5-4c46-b350-0cf1f0b82e03",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "name": "Gertrude Hanson",
        "gender": "female",
        "company": "ROTODYNE",
        "email": "gertrudehanson@rotodyne.com",
        "phone": "+1 (850) 495-2643",
        "about": "Voluptate officia voluptate est reprehenderit qui deserunt enim. Ea ea eu ullamco ea veniam adipisicing do consectetur. Pariatur occaecat Lorem nulla eu minim occaecat. Duis non eu in qui mollit consectetur.\r\n",
        "registered": "2015-01-02T03:18:26 -02:00",
        "latitude": 83.094592,
        "longitude": 179.8049
    },
    {
        "_id": "59fdc1b457acfe86837e36f0",
        "index": 31,
        "guid": "94122646-2ce0-4fbb-8150-982afa05fad8",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 21,
        "name": "Rena Peck",
        "gender": "female",
        "company": "VALREDA",
        "email": "renapeck@valreda.com",
        "phone": "+1 (925) 570-2687",
        "about": "Duis aliquip deserunt laborum amet id consectetur minim voluptate deserunt sint. Id aliquip laborum enim cillum velit. Dolor amet magna est elit ipsum consequat culpa. Consectetur sit aute irure Lorem nulla id ad ipsum esse. Do deserunt qui mollit excepteur. Cillum non excepteur dolor commodo enim exercitation voluptate ullamco tempor.\r\n",
        "registered": "2014-02-08T04:53:58 -02:00",
        "latitude": -61.549509,
        "longitude": 69.440823
    },
    {
        "_id": "59fdc1b40c1693cf66b4bb9a",
        "index": 32,
        "guid": "5c885ea3-f4ea-4a27-96a2-a720d48b2ad6",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 26,
        "name": "Suarez Nieves",
        "gender": "male",
        "company": "TERRAGO",
        "email": "suareznieves@terrago.com",
        "phone": "+1 (826) 417-2293",
        "about": "Eu ipsum nisi sint quis sunt aliqua dolore sunt do ullamco id. Mollit reprehenderit excepteur enim laborum. Adipisicing laborum reprehenderit proident commodo. Ut irure et nostrud dolor esse anim ea adipisicing reprehenderit veniam id laborum. Nulla quis cupidatat irure fugiat ullamco nisi ipsum velit deserunt id deserunt. Esse ex fugiat veniam laborum consectetur. Consequat ad velit laboris in commodo ut aute nisi adipisicing velit minim exercitation irure laborum.\r\n",
        "registered": "2015-06-25T02:11:33 -03:00",
        "latitude": -5.701952,
        "longitude": -106.693217
    },
    {
        "_id": "59fdc1b4a227ae46a2ae87ed",
        "index": 33,
        "guid": "bd8c95ba-b409-4a82-b281-995ceece2367",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Dotson Hyde",
        "gender": "male",
        "company": "ISONUS",
        "email": "dotsonhyde@isonus.com",
        "phone": "+1 (830) 559-2356",
        "about": "Nostrud fugiat commodo eu ex. Eiusmod non proident nulla pariatur reprehenderit enim ea nostrud esse excepteur velit consectetur incididunt ad. Deserunt dolore consectetur labore minim sint voluptate sunt mollit.\r\n",
        "registered": "2016-07-09T06:54:28 -03:00",
        "latitude": 34.339801,
        "longitude": 178.718636
    },
    {
        "_id": "59fdc1b4c044bddbf58d3c97",
        "index": 34,
        "guid": "5ee64e97-35b7-40e5-a726-39be3d164ed3",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 38,
        "name": "Simpson Rasmussen",
        "gender": "male",
        "company": "NORALEX",
        "email": "simpsonrasmussen@noralex.com",
        "phone": "+1 (990) 417-2430",
        "about": "Laborum in sint non id qui voluptate consectetur elit. Quis magna commodo ex deserunt mollit nisi exercitation esse ad esse labore officia. Sint id mollit eu tempor quis elit ut minim labore. Non sunt minim deserunt velit laborum quis labore deserunt fugiat ea nulla adipisicing. Cillum ipsum nisi ad adipisicing nostrud excepteur labore.\r\n",
        "registered": "2017-10-23T04:33:29 -03:00",
        "latitude": -53.775759,
        "longitude": 172.440067
    },
    {
        "_id": "59fdc1b4afad066ab7ba8b72",
        "index": 35,
        "guid": "eadc6908-8527-40f3-93c5-2a0809bf670f",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 28,
        "name": "Gray Wade",
        "gender": "male",
        "company": "KOOGLE",
        "email": "graywade@koogle.com",
        "phone": "+1 (837) 518-2948",
        "about": "Qui veniam proident occaecat labore aliquip dolor proident. In eiusmod proident occaecat irure tempor consectetur sint veniam fugiat consectetur. Nostrud nostrud esse id Lorem occaecat dolor irure. Commodo proident veniam occaecat enim nisi duis qui consequat anim cillum et. Mollit voluptate ipsum ipsum tempor cillum. Labore ex elit qui non voluptate ut velit in enim duis minim ipsum tempor.\r\n",
        "registered": "2017-10-11T02:58:25 -03:00",
        "latitude": 54.932398,
        "longitude": 7.224142
    },
    {
        "_id": "59fdc1b438b1cf1656bf0e9e",
        "index": 36,
        "guid": "62240669-47c7-44bb-a004-03063fad16c0",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "name": "Robbie Mccray",
        "gender": "female",
        "company": "MAGMINA",
        "email": "robbiemccray@magmina.com",
        "phone": "+1 (857) 419-3049",
        "about": "Quis excepteur aliqua minim laboris commodo mollit non. Ut minim ut minim cillum dolore quis aliquip anim qui officia incididunt aliqua mollit. Sit id id excepteur labore et tempor nulla nulla.\r\n",
        "registered": "2015-09-11T02:40:16 -03:00",
        "latitude": -52.37864,
        "longitude": 103.964654
    },
    {
        "_id": "59fdc1b4a9dac6ac92bedaee",
        "index": 37,
        "guid": "9671fd3f-30f8-488d-9417-7008c291816d",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 28,
        "name": "Macias Jennings",
        "gender": "male",
        "company": "SPACEWAX",
        "email": "maciasjennings@spacewax.com",
        "phone": "+1 (968) 462-3013",
        "about": "Aliquip tempor nostrud eu laboris laboris adipisicing proident exercitation. Sunt ut reprehenderit sint proident proident exercitation reprehenderit officia exercitation do dolor aliquip irure. Mollit incididunt minim laboris enim do ex Lorem ut eu eu laboris et. Elit exercitation cupidatat cillum irure non esse officia sit aliqua consectetur sit sunt nisi. Eiusmod ut ut et elit in aute dolore minim sunt irure. Tempor tempor pariatur culpa occaecat adipisicing exercitation laboris aliqua pariatur fugiat laboris tempor quis.\r\n",
        "registered": "2016-09-20T11:00:58 -03:00",
        "latitude": 50.575668,
        "longitude": -178.242975
    },
    {
        "_id": "59fdc1b43ec2ad8cdcca3bc0",
        "index": 38,
        "guid": "ac36bc5e-a7eb-4209-8577-ccb5caa07958",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 30,
        "name": "Pearson Merritt",
        "gender": "male",
        "company": "MANUFACT",
        "email": "pearsonmerritt@manufact.com",
        "phone": "+1 (978) 451-3807",
        "about": "Veniam dolor ex in deserunt magna. Enim veniam Lorem occaecat aute enim minim elit. Veniam non id magna exercitation Lorem elit.\r\n",
        "registered": "2015-03-30T03:36:49 -03:00",
        "latitude": -86.465324,
        "longitude": 133.567086
    },
    {
        "_id": "59fdc1b4ecd6adc0205c353f",
        "index": 39,
        "guid": "1bfe8b22-f510-4371-b272-9c813de027c2",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 31,
        "name": "Verna Savage",
        "gender": "female",
        "company": "INSECTUS",
        "email": "vernasavage@insectus.com",
        "phone": "+1 (886) 441-2898",
        "about": "Dolor incididunt adipisicing incididunt culpa minim ea proident id minim Lorem labore. Pariatur adipisicing non qui eu sint dolore labore. Ut pariatur ad elit in. Esse excepteur laboris consectetur cillum reprehenderit cupidatat amet proident. Quis aute mollit enim Lorem ea est amet sint nisi ipsum.\r\n",
        "registered": "2017-03-04T02:14:50 -02:00",
        "latitude": 12.179603,
        "longitude": 89.823832
    },
    {
        "_id": "59fdc1b42439c5bd20105b5b",
        "index": 40,
        "guid": "e7190b60-bcd7-4732-8bb3-ff1e0dfd9868",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "name": "Myra Barber",
        "gender": "female",
        "company": "PETIGEMS",
        "email": "myrabarber@petigems.com",
        "phone": "+1 (839) 491-2958",
        "about": "Eiusmod laborum culpa deserunt adipisicing. Eiusmod ea proident amet laborum velit laboris dolor. Non culpa enim enim laborum aliqua esse commodo nulla voluptate tempor anim mollit ipsum reprehenderit. Pariatur elit anim nostrud ad et pariatur anim nulla consectetur. Ullamco do ex laboris Lorem duis. Ut consequat quis eu cillum in tempor aute officia duis magna reprehenderit adipisicing.\r\n",
        "registered": "2017-04-05T08:03:33 -03:00",
        "latitude": 49.729656,
        "longitude": -111.697859
    },
    {
        "_id": "59fdc1b479266341609f9800",
        "index": 41,
        "guid": "9403b74d-83c0-482d-9a69-d95ebb13ebec",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 26,
        "name": "Beard Wolf",
        "gender": "male",
        "company": "SHOPABOUT",
        "email": "beardwolf@shopabout.com",
        "phone": "+1 (993) 586-2339",
        "about": "Consectetur qui id enim ea ea laboris. Tempor aute laborum sint anim duis aliqua veniam. Velit aliqua tempor reprehenderit tempor ea non irure adipisicing irure minim. Ad qui commodo laboris et eu duis ipsum. Commodo ad deserunt proident commodo ut fugiat deserunt nostrud. Occaecat est minim fugiat ut aliqua cillum laboris mollit et.\r\n",
        "registered": "2016-09-29T12:28:21 -03:00",
        "latitude": 29.848342,
        "longitude": 36.857313
    },
    {
        "_id": "59fdc1b4242d168cf7ee9ef1",
        "index": 42,
        "guid": "155908db-a5ac-4b91-b2d3-610a500f23a1",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 31,
        "name": "Jane Bradford",
        "gender": "female",
        "company": "VETRON",
        "email": "janebradford@vetron.com",
        "phone": "+1 (956) 447-3029",
        "about": "Eiusmod dolore non est consectetur amet nostrud et duis est laboris anim. Nulla elit pariatur minim et voluptate elit officia consectetur sint quis nisi mollit. Excepteur deserunt fugiat adipisicing consectetur Lorem exercitation fugiat anim. Dolor non officia culpa pariatur. Sunt reprehenderit nostrud proident nisi laborum culpa nulla esse aute ullamco. Magna ad cupidatat exercitation aliqua labore velit pariatur quis et voluptate quis irure tempor reprehenderit. Cillum magna Lorem non fugiat tempor consequat.\r\n",
        "registered": "2015-04-28T06:09:38 -03:00",
        "latitude": 61.40743,
        "longitude": 82.523212
    },
    {
        "_id": "59fdc1b48f71ff9e0f58d430",
        "index": 43,
        "guid": "4175055b-f771-436c-b786-6fc896c78e5c",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 28,
        "name": "Patricia Page",
        "gender": "female",
        "company": "CORECOM",
        "email": "patriciapage@corecom.com",
        "phone": "+1 (873) 515-2549",
        "about": "Officia in ad sint occaecat reprehenderit dolor dolor et voluptate laboris. Laborum cillum non ullamco consequat adipisicing culpa sint sit veniam est. Veniam fugiat aliqua incididunt ut cupidatat velit officia aliqua. Pariatur est qui consectetur cupidatat irure ipsum amet enim ipsum qui ea tempor adipisicing aliquip.\r\n",
        "registered": "2017-02-14T11:29:50 -02:00",
        "latitude": 86.453893,
        "longitude": -0.432294
    },
    {
        "_id": "59fdc1b4e81b89c198fab350",
        "index": 44,
        "guid": "4b9aa215-0e22-4c18-a7b3-a6017184baae",
        "isActive": false,
        "picture": "http://placehold.it/32x32",
        "age": 35,
        "name": "Crane Sullivan",
        "gender": "male",
        "company": "QUAREX",
        "email": "cranesullivan@quarex.com",
        "phone": "+1 (857) 440-3568",
        "about": "Et duis ullamco cillum nisi fugiat commodo et culpa do velit et est proident nisi. Tempor est anim nulla incididunt ad amet dolor dolore cupidatat. Occaecat amet aliqua nisi tempor ut ex nulla. Aliquip culpa incididunt nostrud fugiat ut nulla culpa nostrud ea dolore. Veniam id minim laborum qui magna sunt ex labore ut commodo sunt id.\r\n",
        "registered": "2014-08-30T06:55:52 -03:00",
        "latitude": 89.061687,
        "longitude": -90.455764
    },
    {
        "_id": "59fdc1b4322f70be2c449a23",
        "index": 45,
        "guid": "f05063e1-2099-4ba9-8054-17bf94c83e7a",
        "isActive": true,
        "picture": "http://placehold.it/32x32",
        "age": 37,
        "name": "Isabelle Estes",
        "gender": "female",
        "company": "LIMOZEN",
        "email": "isabelleestes@limozen.com",
        "phone": "+1 (903) 414-2098",
        "about": "Cillum id ad in pariatur sit irure consectetur. Deserunt ea nisi nostrud enim laboris do. Ex veniam aute incididunt non occaecat sunt ut sunt deserunt velit.\r\n",
        "registered": "2016-10-06T06:44:28 -03:00",
        "latitude": -63.698771,
        "longitude": -79.175464
    }
];

class UserService {
    constructor($q) {
        "ngInject";
        this._$q = $q;
    }

    /**
     * Returns a list of users from the API
     * @param limit
     */
    getUsers(limit = 100) {
        // TODO: remove the dependecy on this._$q;
        let defer = this._$q.defer();
        defer.resolve(this.parseUsers(users.slice(0, limit)));
        return defer.promise;
    }

    parseUsers(users) {
        return users.map(user => {
            user[COORDINATES_KEYNAME] = {
                [LATITUDE_KEYNAME]: user[LATITUDE_KEYNAME],
                [LONGTITUDE_KEYNAME]: user[LONGTITUDE_KEYNAME]
            };
            return user;
        });
    }

    loadInitUsers() {
        return this.getUsers(10)
            .catch(e => console.error(e));
    }
}

export default UserService;